name: silvernote
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  clerk_flutter: ^0.0.12-beta
  connectivity_plus: ^7.0.0
  http: ^1.5.0
  webview_flutter_android: ^4.10.2
  webview_flutter: ^4.13.0
  webview_cookie_manager_flutter: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  html: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets\icon\favicon.png